Change cov in EstimationStep from bool to string
pharmpy/pharmpy pull request #1805
Opened 2023-06-26 12:39 UTC by vrognas

2023-06-26 13:26 UTC, stellabelin requested changes
Looks good! Some minor comments (only the first one is necessary), `docs-test` are also failing.

2023-06-26 13:28 UTC, rikardn requested changes
Thanks for the PR. I found one thing in update

2023-06-26 13:28 UTC, rikardn commented on src/pharmpy/model/external/nonmem/update.py
> +        elif est.cov is not None and est.cov in EstimationStep.supported_covs:
No need to check if in supported_covs since this is an invariant. If it is not None it has to be supported.

2023-06-26 13:28 UTC, rikardn commented on src/pharmpy/model/external/nonmem/update.py
> +        elif est.cov is not None and est.cov in EstimationStep.supported_covs:
Same as above

2023-06-28 14:42 UTC, stellabelin approved these changes
LGTM!

2023-06-28 14:47 UTC, merged