COVsearch update
pharmpy/pharmpy pull request #2215
Opened 2023-10-18 12:01 UTC by JohanWBorg

Implemented covariate as a part of ModelFeatures and changes to covsearch for handling of already present covariates
- Covariate attribute is now a part of ModelFeautures, allowing addition, subtraction and least number of transformation between different models/search spaces
- Possibility of extracting covariates from a model of choosing, with effect (based on our effect templates) and operator using "get_covariates()". Also implemented this feature within "get_model_features()"
- Changes to covsearch to handle already present covariates. If present covariates is not part of search space, they are removed before running covsearch. If they are a part of the model and the search space, they are left as is and are removed from the search space.

2023-10-20 08:17 UTC, rikardn commented
@JohanWBorg Could you have a look at the conflicts?

2023-10-25 14:41 UTC, JohanWBorg commented
@rikardn Conflicts should be resolved now

2023-10-26 14:04 UTC, rikardn requested changes

2023-10-26 14:04 UTC, rikardn commented on src/pharmpy/modeling/covariate_effect.py
> +def get_covariates(model: Model):
Need return type hint for the pharmr code generation

2023-10-26 14:04 UTC, rikardn commented on src/pharmpy/tools/mfl/parse.py
> +        # if any([v[0][0] == 'custom' for _, v in covariates.items()]):
Remove commented code

2023-10-31 14:23 UTC, merged