Find clearance and volume parameters in model
pharmpy/pharmpy pull request #815
Opened 2022-05-12 13:18 UTC by ZheHuang96

Hi Rikard,

This PR is the first version of finding clearance and volume parameters. I will change the allometry code in the next PR when these two functions are OK.

Best regards,
Zhe Huang

2022-05-12 15:25 UTC, rikardn requested changes

2022-05-13 06:47 UTC, ZheHuang96 commented
No problem, I will do it now!

2022-05-17 06:30 UTC, rikardn requested changes

2022-05-17 06:30 UTC, rikardn commented on src/pharmpy/modeling/odes.py
> +     >>> find_volume_parameters(model)
This will not pass the doctest

2022-05-17 06:30 UTC, rikardn commented on src/pharmpy/modeling/odes.py
> +     >>> find_clearance_parameters(model)
This will not pass the doctest

2022-05-17 06:30 UTC, rikardn commented on src/pharmpy/modeling/odes.py
> +def find_clearance_parameters(model):
Function needs to be added to `modeling/__init__.py`

2022-05-17 06:30 UTC, rikardn commented on src/pharmpy/modeling/odes.py
> +def find_volume_parameters(model):
Function needs to be added to `modeling/__init__.py`

2022-05-17 07:32 UTC, ZheHuang96 commented
Sorry I forgot them, I will add it now.

2022-05-17 08:22 UTC, rikardn commented on src/pharmpy/modeling/odes.py
> +     >>> find_volume_parameters(model)
You need to add the function to the `__init__.py` then do `tox -e docs,doctest`. It should fail since no output from the function call is given.

2022-05-17 12:33 UTC, ZheHuang96 commented
Sorry, I accidentally rebase my branch... I will find a way to cancel the rebase and push again.

2022-05-17 14:09 UTC, rikardn approved these changes

2022-05-17 14:09 UTC, merged