Add model object as input of amd function
pharmpy/pharmpy pull request #841
Opened 2022-05-24 12:52 UTC by ZheHuang96

Hi Rikard,

This PR is a very basic version of adding the model object as the input of AMD function. There are also some things I am not very sure about:

 My understanding is if we want to use the model object as the starting point, we should have a pharmpy model or do `model=read_model(path)`, then we do `run_amd(model, ...)`. The benefit is the flexibility of input, `run_amd` can follow some functions which return a model object (I think?). But this is just my intuitive feeling.

Another possibility to deal with it is to give a path of the mod file and let the AMD function handle different situations. For example, we can have `path= '~/xxx.mod' ` or `path= '~/xxx.csv'` and we convert model inside our AMD function. 

Which one do you think is more user-friendly?

Best regards,
Zhe Huang

2022-05-25 12:34 UTC, rikardn requested changes

2022-05-25 13:04 UTC, rikardn commented on src/pharmpy/modeling/amd.py
> +    if type(input) is str and input.endswith('.csv'):
True, but we might support other types in the future and some users might not have used the .csv extension even though the file is csv

2022-05-25 13:04 UTC, ZheHuang96 commented on src/pharmpy/modeling/amd.py
> +    if type(input) is str and input.endswith('.csv'):
But maybe we should let the user input the correct dataset so that we don't need to check whether it is a CSV file or not

2022-05-25 13:05 UTC, ZheHuang96 commented on src/pharmpy/modeling/amd.py
> +    if type(input) is str and input.endswith('.csv'):
Ok, thank you for your reply! I will correct it now!

2022-05-25 13:13 UTC, ZheHuang96 commented
> In the case of a model I think we should require the input of a model object. In the command line interface later on we could allow a path to a model.

I agree! And I feel like it will be super cool to run it directly on the command line:)

2022-05-30 08:43 UTC, merged

2022-05-30 08:43 UTC, rikardn commented
Thanks!